version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - pip install unittest2
      - pip install boto3
      - python -m unittest discover tests
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
